# Generated by Django 2.1 on 2018-08-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumnail_image', models.ImageField(upload_to='')),
                ('item_title', models.CharField(max_length=20)),
                ('item_content', models.TextField()),
                ('github_link', models.URLField()),
            ],
        ),
    ]
