# Generated by Django 2.1 on 2018-08-08 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='github_link',
            new_name='item_link',
        ),
    ]
